"""
app/services/code_generator_service.py
─────────────────────────────────────────────────────────────────────────────
Source-Code Generation Service

Implements spec section 3:
   "The platform should generate corresponding source code/scripts to
    automate each process step.  Generated code may include:
      • ETL Scripts
      • Pipeline Configurations
      • Transformation Logic
      • Deployment-ready automation code"

When the user clicks the new **Download the Code** dropdown entry on the
Suggestion Details page, this service builds an in-memory ZIP containing:

  agentforgex_<suggestion_slug>/
    README.md
    requirements.txt
    config/
        pipeline.yaml
        connections.yaml
    src/
        orchestrator.py          (LangGraph-style orchestrator skeleton)
        agents/
            <agent_name>.py      (one per detected agent)
        tools/
            <tool_name>.py       (one per detected tool)
        etl/
            extract.py
            transform.py
            load.py
    scripts/
        run_local.sh
        deploy.sh
    tests/
        test_orchestrator.py

The content is *fully dynamic* — every file is generated from the
suggestion + process + technical-design payload, so the user can clone &
run a meaningful skeleton, not boilerplate.
"""

from __future__ import annotations

import io
import logging
import re
import textwrap
import zipfile
from datetime import datetime
from typing import Any, Dict, List, Optional

from app.core.mistral_client import get_mistral_client

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────
def _slugify(s: str) -> str:
    s = (s or "agent").lower()
    s = re.sub(r"[^a-z0-9]+", "_", s).strip("_")
    return s or "agent"


def _safe_name(s: str) -> str:
    return _slugify(s).replace("__", "_")


def _wrap(s: str) -> str:
    return textwrap.dedent(s).strip() + "\n"


# ─────────────────────────────────────────────────────────────────────────────
# Code templates — each accepts simple context dicts and returns text.
# Kept intentionally readable so generated output is review-friendly.
# ─────────────────────────────────────────────────────────────────────────────
def _tpl_readme(ctx: Dict[str, Any]) -> str:
    suggestion_title = ctx["suggestion_title"]
    process_title    = ctx["process_title"]
    agents           = ctx["agents"]
    tools            = ctx["tools"]

    agent_md = "\n".join(f"- **{a['name']}** — {a.get('role', '')}" for a in agents) or "(none)"
    tool_md  = "\n".join(f"- **{t['name']}** — {t.get('purpose', '')}" for t in tools) or "(none)"

    return _wrap(f"""
    # {suggestion_title}

    Auto-generated automation scaffold for the **{process_title}** process,
    produced by **AgentForgeX**.

    Generated on: {ctx['generated_at']}
    Suggestion ID: `{ctx['suggestion_id']}`

    ## What's in this bundle?

    ```
    {_safe_name(suggestion_title)}/
        README.md
        requirements.txt
        config/
            pipeline.yaml
            connections.yaml
        src/
            orchestrator.py
            agents/
            tools/
            etl/
        scripts/
            run_local.sh
            deploy.sh
        tests/
            test_orchestrator.py
    ```

    ## Agents

    {agent_md}

    ## Tools / Connectors

    {tool_md}

    ## Quick start (local dev)

    ```bash
    python -m venv .venv && source .venv/bin/activate
    pip install -r requirements.txt
    cp config/connections.yaml.example config/connections.yaml   # then edit
    bash scripts/run_local.sh
    ```

    ## Disclaimer

    This scaffold is a starting point.  Wire up real connectors, secrets,
    and policy files before running against production data.
    """)


def _tpl_requirements() -> str:
    return _wrap("""
    # Generated by AgentForgeX
    fastapi==0.110.0
    uvicorn[standard]==0.27.1
    pydantic==2.6.1
    httpx==0.27.0
    pyyaml==6.0.1
    python-dotenv==1.0.1
    structlog==24.1.0

    # Agentic stack
    langgraph==0.0.40
    langchain-core==0.1.30
    openai==1.13.3

    # Data plane
    pandas==2.2.1
    sqlalchemy==2.0.27
    pyodbc==5.1.0          ; sys_platform != "darwin"

    # Tests
    pytest==8.0.2
    pytest-asyncio==0.23.5
    """)


def _tpl_pipeline_yaml(ctx: Dict[str, Any]) -> str:
    return _wrap(f"""
    # config/pipeline.yaml — generated by AgentForgeX
    pipeline:
      name: {_safe_name(ctx['suggestion_title'])}
      process: "{ctx['process_title']}"
      version: 1
      runtime: "python:3.11"
      entrypoint: "src.orchestrator:main"

    schedule:
      type: cron
      expression: "0 */6 * * *"   # every 6 hours by default

    steps:
""") + "".join(
    f"""  - id: {_safe_name(s.get('title', f'step_{i}'))}
    title: "{s.get('title','step ' + str(i))}"
    type: {s.get('step_type') or 'process'}
    actor: "{s.get('actor', 'process')}"
    automation_potential: {s.get('automation_potential', 0)}
"""
    for i, s in enumerate(ctx["steps"][:25], start=1)
)


def _tpl_connections_yaml(ctx: Dict[str, Any]) -> str:
    src_name = ctx["data_lineage"].get("data_source", {}).get("name", "ADF (Azure Data Factory)")
    tgt_name = ctx["data_lineage"].get("data_target", {}).get("name", "Downstream Process System")
    return _wrap(f"""
    # config/connections.yaml — generated by AgentForgeX
    #
    # Defaults below come from the document data-lineage detection.  Replace
    # every <SECRET-*> placeholder before running in any non-local environment.

    source:
      name: "{src_name}"
      type: "{ctx['data_lineage'].get('data_source', {}).get('type', 'Source System')}"
      connection:
        url: "<SECRET-SOURCE-URL>"
        auth_method: "oauth2_client_credentials"
        client_id: "<SECRET-SOURCE-CLIENT-ID>"
        client_secret: "<SECRET-SOURCE-CLIENT-SECRET>"

    target:
      name: "{tgt_name}"
      type: "{ctx['data_lineage'].get('data_target', {}).get('type', 'Downstream System')}"
      connection:
        url: "<SECRET-TARGET-URL>"
        auth_method: "bearer_token"
        token: "<SECRET-TARGET-TOKEN>"

    llm:
      provider: "openai"          # or "mistral", "anthropic"
      api_key: "<SECRET-LLM-API-KEY>"
      model: "gpt-4o"

    observability:
      logging_level: "INFO"
      otel_endpoint: "<SECRET-OTEL-ENDPOINT>"
    """)


def _tpl_orchestrator(ctx: Dict[str, Any]) -> str:
    agents = ctx["agents"]
    agent_imports = "\n".join(
        f"from src.agents.{_safe_name(a['name'])} import {_class_name(a['name'])}"
        for a in agents
    )
    agent_init = "\n        ".join(
        f"self.{_safe_name(a['name'])} = {_class_name(a['name'])}(cfg)"
        for a in agents
    )
    return _wrap(f'''
    """
    Orchestrator skeleton — wires individual agents into a LangGraph-style
    state machine.  Generated by AgentForgeX from the technical design.

    Replace the placeholder `_decide_next` logic with the real routing once
    real connectors are wired in.
    """
    from __future__ import annotations

    import logging
    import yaml
    from pathlib import Path

    {agent_imports}

    log = logging.getLogger("orchestrator")


    def _load_config():
        p = Path(__file__).resolve().parent.parent / "config" / "connections.yaml"
        with p.open() as f:
            return yaml.safe_load(f) or {{}}


    class Orchestrator:
        """Plan-and-Execute orchestrator for {ctx['suggestion_title']!r}."""

        def __init__(self, cfg: dict | None = None):
            cfg = cfg or _load_config()
            {agent_init or "pass"}
            self._cfg = cfg

        def run(self, payload: dict) -> dict:
            log.info("orchestrator.start", extra={{"payload": payload}})
            state = {{"payload": payload, "trace": []}}
''') + _orchestrator_steps_block(agents) + _wrap("""
            log.info("orchestrator.done", extra={"state": state})
            return state

        def _decide_next(self, state: dict) -> str:
            # TODO: replace with policy-driven routing
            return "done"


    def main():
        logging.basicConfig(level=logging.INFO)
        Orchestrator().run({"hello": "world"})


    if __name__ == "__main__":
        main()
""")


def _orchestrator_steps_block(agents: List[Dict[str, Any]]) -> str:
    if not agents:
        return _wrap("            state['trace'].append('no_agents_configured')\n")
    lines = []
    for a in agents:
        name = _safe_name(a["name"])
        lines.append(f"            state = self.{name}.handle(state)")
        lines.append(f'            state["trace"].append("{name}")')
    return "\n".join(lines) + "\n"


def _class_name(s: str) -> str:
    parts = [p for p in re.split(r"[^A-Za-z0-9]+", s or "Agent") if p]
    return "".join(p.capitalize() for p in parts) or "Agent"


def _tpl_agent(agent: Dict[str, Any]) -> str:
    cls = _class_name(agent.get("name", "Agent"))
    name = agent.get("name", "Agent")
    role = agent.get("role", "Specialist agent.")
    resp = agent.get("responsibilities", []) or []
    resp_md = "\n".join(f"      • {r}" for r in resp) or "      (none documented)"
    framework = agent.get("reasoning_framework") or "Plan-and-Execute"
    model = agent.get("model_tier") or "gpt-4o"
    return _wrap(f'''
    """
    {name}
    Role: {role}

    Reasoning framework: {framework}
    Model tier:          {model}

    Responsibilities:
{resp_md}
    """
    from __future__ import annotations

    import logging

    log = logging.getLogger("{_safe_name(name)}")


    class {cls}:
        FRAMEWORK = "{framework}"
        MODEL     = "{model}"

        def __init__(self, cfg: dict | None = None):
            self.cfg = cfg or {{}}

        def handle(self, state: dict) -> dict:
            log.info("agent.{_safe_name(name)}.start")
            # TODO: implement the {role.lower()} loop here.
            # 1. Read inputs from `state`
            # 2. Call any tools required (see src/tools/)
            # 3. Return updated state
            state.setdefault("agent_outputs", {{}})["{_safe_name(name)}"] = {{
                "status": "stub",
                "message": "Replace with real agent logic.",
            }}
            return state
    ''')


def _tpl_tool(tool: Dict[str, Any]) -> str:
    name = tool.get("tool_name") or tool.get("name") or "Tool"
    cls = _class_name(name)
    purpose = tool.get("purpose") or "Generic tool."
    invoked_by = tool.get("invoked_by") or "any agent"
    return _wrap(f'''
    """
    {name}
    Purpose:    {purpose}
    Invoked by: {invoked_by}
    """
    from __future__ import annotations


    class {cls}:
        def __init__(self, cfg: dict | None = None):
            self.cfg = cfg or {{}}

        def call(self, **kwargs):
            # TODO: implement tool integration.
            return {{"ok": True, "result": None}}
    ''')


def _tpl_etl_extract() -> str:
    return _wrap('''
    """ETL — extract phase.  Reads from the configured source system."""
    from __future__ import annotations

    import logging
    import yaml
    from pathlib import Path

    log = logging.getLogger("etl.extract")


    def load_source_cfg():
        p = Path(__file__).resolve().parent.parent.parent / "config" / "connections.yaml"
        with p.open() as f:
            return (yaml.safe_load(f) or {}).get("source", {})


    def extract(query: str | None = None):
        cfg = load_source_cfg()
        log.info("extract.start", extra={"source": cfg.get("name")})
        # TODO: replace with real connector logic
        return {"rows": [], "source": cfg.get("name")}


    if __name__ == "__main__":
        logging.basicConfig(level=logging.INFO)
        print(extract())
    ''')


def _tpl_etl_transform() -> str:
    return _wrap('''
    """ETL — transform phase. Applies business rules to extracted rows."""
    from __future__ import annotations

    from typing import Iterable


    def transform(rows: Iterable[dict]) -> list[dict]:
        # TODO: replace with the policy-driven transformations from
        # the technical design's "Transformation Logic" section.
        return [dict(r) for r in rows]
    ''')


def _tpl_etl_load() -> str:
    return _wrap('''
    """ETL — load phase. Writes transformed rows to the target system."""
    from __future__ import annotations

    import logging
    import yaml
    from pathlib import Path

    log = logging.getLogger("etl.load")


    def load_target_cfg():
        p = Path(__file__).resolve().parent.parent.parent / "config" / "connections.yaml"
        with p.open() as f:
            return (yaml.safe_load(f) or {}).get("target", {})


    def load(rows: list[dict]):
        cfg = load_target_cfg()
        log.info("load.start", extra={"target": cfg.get("name"), "n_rows": len(rows)})
        # TODO: replace with real write logic
        return {"written": len(rows), "target": cfg.get("name")}
    ''')


def _tpl_run_local_sh() -> str:
    return _wrap('''
    #!/usr/bin/env bash
    # Generated by AgentForgeX — runs the orchestrator locally end-to-end.
    set -euo pipefail
    cd "$(dirname "$0")/.."
    export PYTHONPATH="${PYTHONPATH:-}:$(pwd)"
    python -m src.orchestrator
    ''')


def _tpl_deploy_sh() -> str:
    return _wrap('''
    #!/usr/bin/env bash
    # Generated by AgentForgeX — deployment scaffold.
    set -euo pipefail
    cd "$(dirname "$0")/.."

    docker build -t agentforgex/$(basename "$(pwd)") .
    # TODO: push to your registry, then trigger your environment's rollout.
    ''')


def _tpl_test_orch() -> str:
    return _wrap('''
    """Smoke test for the orchestrator skeleton."""
    from src.orchestrator import Orchestrator


    def test_orchestrator_runs():
        result = Orchestrator(cfg={}).run({"hello": "world"})
        assert "trace" in result
    ''')


# ─────────────────────────────────────────────────────────────────────────────
# Public entry point
# ─────────────────────────────────────────────────────────────────────────────
def build_code_zip(
    suggestion: Dict[str, Any],
    process: Dict[str, Any],
    steps: List[Dict[str, Any]],
    technical_design: Dict[str, Any],
    data_lineage: Optional[Dict[str, Any]] = None,
) -> bytes:
    """
    Returns the raw bytes of a ZIP file containing the scaffold.
    Safe to send directly from a Flask endpoint via send_file or Response.
    """
    suggestion_title = (
        suggestion.get("title") or suggestion.get("name") or "Agentic Automation"
    )
    process_title = (
        process.get("title") or process.get("name") or "Business Process"
    )

    # Pull agents + tools straight from the technical-design payload.
    # We prefer the top-level fields since Layer 3 (Agentic Core) is intentionally omitted from architecture_layers.
    agents_raw = technical_design.get("agents", [])
    tools_raw = technical_design.get("tools", [])

    agents: List[Dict[str, Any]] = []
    tools:  List[Dict[str, Any]] = []

    for a in agents_raw:
        if isinstance(a, dict):
            agents.append({
                "name":                  a.get("name", "Agent"),
                "role":                  a.get("role", ""),
                "responsibilities":      a.get("responsibilities") or [],
                "reasoning_framework":   a.get("reasoning_framework"),
                "model_tier":            a.get("model_tier"),
            })

    for t in tools_raw:
        if isinstance(t, dict):
            tools.append({
                "name":        t.get("tool_name") or t.get("name") or "Tool",
                "tool_name":   t.get("tool_name") or t.get("name") or "Tool",
                "purpose":     t.get("purpose", ""),
                "invoked_by":  t.get("invoked_by", ""),
            })

    # Deduplicate by name to avoid double files
    seen_a, uniq_a = set(), []
    for a in agents:
        k = _safe_name(a["name"])
        if k not in seen_a:
            uniq_a.append(a)
            seen_a.add(k)
    agents = uniq_a

    seen_t, uniq_t = set(), []
    for t in tools:
        k = _safe_name(t["name"])
        if k not in seen_t:
            uniq_t.append(t)
            seen_t.add(k)
    tools = uniq_t

    ctx = {
        "suggestion_id":    suggestion.get("_key") or suggestion.get("id") or "n/a",
        "suggestion_title": suggestion_title,
        "process_title":    process_title,
        "steps":            steps or [],
        "agents":           agents,
        "tools":            tools,
        "data_lineage":     data_lineage or {
            "data_source": {"name": "ADF (Azure Data Factory)", "type": "Data Integration Service"},
            "data_target": {"name": "Downstream Process System", "type": "Downstream System"},
        },
        "generated_at":     datetime.utcnow().isoformat(timespec="seconds") + "Z",
    }

    pkg_root = _safe_name(suggestion_title)
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{pkg_root}/README.md",                _tpl_readme(ctx))
        zf.writestr(f"{pkg_root}/requirements.txt",          _tpl_requirements())
        zf.writestr(f"{pkg_root}/config/pipeline.yaml",      _tpl_pipeline_yaml(ctx))
        zf.writestr(f"{pkg_root}/config/connections.yaml",   _tpl_connections_yaml(ctx))
        zf.writestr(f"{pkg_root}/src/__init__.py",           "")
        zf.writestr(f"{pkg_root}/src/orchestrator.py",       _tpl_orchestrator(ctx))
        zf.writestr(f"{pkg_root}/src/agents/__init__.py",    "")
        for a in agents:
            zf.writestr(
                f"{pkg_root}/src/agents/{_safe_name(a['name'])}.py",
                _tpl_agent(a),
            )
        zf.writestr(f"{pkg_root}/src/tools/__init__.py",     "")
        for t in tools:
            zf.writestr(
                f"{pkg_root}/src/tools/{_safe_name(t['name'])}.py",
                _tpl_tool(t),
            )
        zf.writestr(f"{pkg_root}/src/etl/__init__.py",       "")
        zf.writestr(f"{pkg_root}/src/etl/extract.py",        _tpl_etl_extract())
        zf.writestr(f"{pkg_root}/src/etl/transform.py",      _tpl_etl_transform())
        zf.writestr(f"{pkg_root}/src/etl/load.py",           _tpl_etl_load())
        zf.writestr(f"{pkg_root}/scripts/run_local.sh",      _tpl_run_local_sh())
        zf.writestr(f"{pkg_root}/scripts/deploy.sh",         _tpl_deploy_sh())
        zf.writestr(f"{pkg_root}/tests/__init__.py",         "")
        zf.writestr(f"{pkg_root}/tests/test_orchestrator.py", _tpl_test_orch())

    return buf.getvalue()
